# ruff.toml for ROS projects

line-length = 79

[format]
quote-style = "single"

[lint]
select = ["E", "F", "D", "W"]     # enable pyflakes, pycodestyle, and pydocstyle-like rules
ignore = [
    "D203",  # one-blank-line-before-class, conflicts with D211
    "D212",  # multi-line-summary-second-line, conflicts with D212
]